- name: Check if we already in a swarm mode
  shell: "docker info | egrep '^Swarm: ' | cut -d ' ' -f2"
  register: swarm_status

- name: 
  set_fact:
    swarm: true
  when: swarm_status.stdout != "inactive"

- name: Assign master
  set_fact: 
    master: "{{ groups.all | first }}"
  when: swarm is not defined

- name: Enable swarm mode on a cluster
  shell: "docker swarm init --advertise-addr {{ hostvars[master].ansible_wlan0.ipv4.address }}"
  when: "{{ hostvars[inventory_hostname].ansible_hostname == hostvars[master].ansible_hostname }}"

- name: Get the join token
  shell: "docker swarm join-token worker -q"
  register: worker_token
  when: "{{ hostvars[inventory_hostname].ansible_hostname == hostvars[master].ansible_hostname }}"

- name: Add workers to the cluster
  shell: "docker swarm join --token {{ hostvars[master].worker_token.stdout}}  {{ hostvars[master].ansible_wlan0.ipv4.address}}:2377"  
  when: "{{ hostvars[inventory_hostname].ansible_hostname != hostvars[master].ansible_hostname }}"
